version: "3.8"
services:
  study-board-redis:
    container_name: study-board-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: wk/study-board-redis
    ports:
      - "6379:6379"
  study-board-database:
    container_name: study-board-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: wk/study-board-database
    environment:
      - MYSQL_DATABASE=study-board
      - MYSQL_ROOT_PASSWORD=${MY_MYSQL_PW}
    volumes:
      - ./database/config:/etc/mysql/conf.d
#      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
