spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 1MB # 파일 하나의 최대 사이즈
      max-request-size: 10MB # 전체 사이즈

  messages:
    basename: messages,errors

server:
  servlet:
    session:
      tracking-modes=cookie: cookie

logging:
  level:
    org.apache.coyote.http11: trace
    org.hibernate.SQL: debug

file:
  dir: /G:/ # 파일 저장 위치(업로드시)

kakao:
  rest_api:
    client_id: ${KAKAO_REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI}