name: Build and Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUCKET_NAME: study-board-s3
  CODE_DEPLOY_APP_NAME: study-board-codedep
  DEPLOYMENT_GROUP_NAME: board_instance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Github Repository Secrets를 통해 환경 변수 파일 생성
      - name: Generate Environment Variables File for Production
        run: |
          echo "KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID" >> .env
          echo "KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET" >> .env
          echo "AWS_MYSQL_PW=$AWS_MYSQL_PW" >> .env
          echo "AWS_IP=$AWS_IP" >> .env
          echo "GMAIL=$GMAIL" >> .env
          echo "GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD" >> .env
        env:
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID}}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET}}
          AWS_MYSQL_PW: ${{ secrets.AWS_MYSQL_PW}}
          AWS_IP: ${{ secrets.AWS_IP}}
          GMAIL: ${{ secrets.GMAIL}}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD}}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build test

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
